# Generated by Django 4.0 on 2021-12-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descripition',
            new_name='description',
        ),
    ]
