# Generated by Django 4.0 on 2021-12-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_descripition_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
