# Generated by Django 4.0 on 2021-12-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descriptions',
        ),
    ]
